### ISSUE TITLE
This extension is now spyware

### ISSUE THREAD

**Issue by tstrass** [richmondwatkins/RedditCommentCompanion#4] opened 2017-06-27 00:27 UTC
Please revoke the required permissions for reading/changing reddit data and reading browsing history. This has been a great extension. It would be a huge shame if it's really just becoming spyware. @richmondwatkins

**Comment by richmondwatkins** [comment] 2017-06-27 00:39
So it looks like I accidentally left the 'tabs' permission in there. https://developer.chrome.com/extensions/permission_warnings

I had done some work a while ago to add voting but never finished it. Then today I did a quick update so it was just left in there. The reddit permission has always been there though. All that is doing is allowing the extension to to execute javascript on all of reddit's pages. The javascript is what runs the entire thing. The storage setting is what allows me to save simple user settings like 'hover off to close'. 

I haven't updated this repo in a while but I'll push everything that will be in the next release now. You can see for yourself that there isn't anything suspicious going on.

**Closed as completed** 2017-06-27 00:42 UTC

**Comment by tstrass** [comment] 2017-06-27 00:49
Ok well thank you. But Chrome notified me that I needed to grant those two as new permissions. What's with the browsing history? @richmondwatkins

**Comment by richmondwatkins** [comment] 2017-06-27 00:53
I think that was caused by the "tabs" permission that was accidentally added. At the time I was creating a system that would launch a small window for reddit authentication (when I was trying to add voting). It looks like that permission is what generated that warning. The permissions are reverted back to just "storage" now and the update is processing.

**Comment by tstrass** [comment] 2017-06-27 00:57
Alright well thanks for clarifying
